export const GESTURES = {
  YUTA_VIOLET: {
    id: 'YUTA_VIOLET',
    label: 'Yuta Violet',
    coreColor: '#FFB3FF', // bright pink-violet highlight (not white)
    color: '#F358F3',
    secondaryColor: null,
    particleCount: 5500,
    orbRadius: 0.08,
    coreRadius: 0.22,
    rimRadius: 0.85,
    colorVariation: 0.14,
    behavior: 'neutral',
  },
  RYU_CYAN: {
    id: 'RYU_CYAN',
    label: 'Ryu Cyan',
    coreColor: '#DAFFF9', // very light cyan highlight
    color: '#97F4EB',
    secondaryColor: null,
    particleCount: 5000,
    orbRadius: 0.07,
    coreRadius: 0.20,
    rimRadius: 0.80,
    colorVariation: 0.12,
    behavior: 'directional',
  },
  GOJO_RED: {
    id: 'GOJO_RED',
    label: 'Gojo Red',
    coreColor: '#FF8888', // bright warm-red highlight
    color: '#FD093F',
    secondaryColor: '#8B0000',
    particleCount: 7000,
    orbRadius: 0.10,
    coreRadius: 0.20,
    rimRadius: 0.85,
    colorVariation: 0.18,
    behavior: 'repulsion',
  },
  GOJO_BLUE: {
    id: 'GOJO_BLUE',
    label: 'Gojo Blue',
    coreColor: '#A0F8FF', // bright cyan-blue highlight
    color: '#03CEDB',
    secondaryColor: '#0018A8',
    particleCount: 7000,
    orbRadius: 0.10,
    coreRadius: 0.22,
    rimRadius: 0.86,
    colorVariation: 0.14,
    behavior: 'attraction',
  },
  HOLLOW_PURPLE: {
    id: 'HOLLOW_PURPLE',
    label: 'Hollow Purple',
    coreColor: '#E080FF', // bright saturated purple highlight
    color: '#A844CC',
    secondaryColor: '#03CEDB',
    particleCount: 9000,
    orbRadius: 0.12,
    coreRadius: 0.26,
    rimRadius: 0.92,
    colorVariation: 0.18,
    behavior: 'oscillate',
  },
  INFINITE_VOID: {
    id: 'INFINITE_VOID',
    label: 'Infinite Void',
    fullscreen: true,
  },
};
