export const GESTURES = {
  YUTA_VIOLET: {
    id: 'YUTA_VIOLET',
    color: '#8B00FF',
    secondaryColor: null,
    particleCount: 3000,
    orbRadius: 0.08,
    behavior: 'neutral',
    label: 'Yuta Violet',
  },
  RIKA_CYAN: {
    id: 'RIKA_CYAN',
    color: '#00FFFF',
    secondaryColor: null,
    particleCount: 2500,
    orbRadius: 0.06,
    behavior: 'directional',
    label: 'Rika Cyan',
  },
  GOJO_RED: {
    id: 'GOJO_RED',
    color: '#FF2200',
    secondaryColor: null,
    particleCount: 3000,
    orbRadius: 0.09,
    behavior: 'repulsion',
    label: 'Gojo Red',
  },
  GOJO_BLUE: {
    id: 'GOJO_BLUE',
    color: '#0044FF',
    secondaryColor: null,
    particleCount: 3500,
    orbRadius: 0.10,
    behavior: 'attraction',
    label: 'Gojo Blue',
  },
  HOLLOW_PURPLE: {
    id: 'HOLLOW_PURPLE',
    color: '#CC00FF',
    secondaryColor: '#0044FF',
    particleCount: 5000,
    orbRadius: 0.12,
    behavior: 'oscillate',
    label: 'Hollow Purple',
  },
};
